export const emergencyListingRows = [
  {
    "id": "l_1777596930523_mmqlb",
    "title": "why",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777596930523,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777596176125_whdb7",
    "title": "ㅗ노뉴눈",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777596176125,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594432613_99lhm",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594432613,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594288648_p9rn2",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594288648,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594288489_x24rd",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594288489,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594288269_j1myo",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594288269,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594287805_qohpc",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594287805,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594286175_yrp1l",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594286175,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594257959_c3jx9",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "rt_2room_sep",
    "city": "incheon_seo",
    "area": "인천 서구 공촌동 307-16",
    "address": "인천 서구 공촌동 307-16",
    "monthly_rent": 500000,
    "deposit": 500000,
    "maintenance_fee": 40000,
    "maintenance_included": false,
    "floor": "1",
    "size": 0,
    "subway_station": "아시아드경기장역",
    "subway_minutes": 14,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "interphone",
      "elevator",
      "parking"
    ],
    "description": "Инчонд кошир тусдаа 2өрөө байр✨✨✨\n📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт\nБарьцаа:500,000\nТүрээс:500,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594257959,
    "payment_type": "quarterly",
    "latitude": 37.55095,
    "longitude": 126.69262,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594257784_ari90",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "rt_2room_sep",
    "city": "incheon_seo",
    "area": "인천 서구 공촌동 307-16",
    "address": "인천 서구 공촌동 307-16",
    "monthly_rent": 500000,
    "deposit": 500000,
    "maintenance_fee": 40000,
    "maintenance_included": false,
    "floor": "1",
    "size": 0,
    "subway_station": "아시아드경기장역",
    "subway_minutes": 14,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "interphone",
      "elevator",
      "parking"
    ],
    "description": "Инчонд кошир тусдаа 2өрөө байр✨✨✨\n📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт\nБарьцаа:500,000\nТүрээс:500,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594257784,
    "payment_type": "quarterly",
    "latitude": 37.55095,
    "longitude": 126.69262,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594256950_dmzzk",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "rt_2room_sep",
    "city": "incheon_seo",
    "area": "인천 서구 공촌동 307-16",
    "address": "인천 서구 공촌동 307-16",
    "monthly_rent": 500000,
    "deposit": 500000,
    "maintenance_fee": 40000,
    "maintenance_included": false,
    "floor": "1",
    "size": 0,
    "subway_station": "아시아드경기장역",
    "subway_minutes": 14,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "interphone",
      "elevator",
      "parking"
    ],
    "description": "Инчонд кошир тусдаа 2өрөө байр✨✨✨\n📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт\nБарьцаа:500,000\nТүрээс:500,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594256950,
    "payment_type": "quarterly",
    "latitude": 37.55095,
    "longitude": 126.69262,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594256106_or1oz",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "rt_2room_sep",
    "city": "incheon_seo",
    "area": "인천 서구 공촌동 307-16",
    "address": "인천 서구 공촌동 307-16",
    "monthly_rent": 500000,
    "deposit": 500000,
    "maintenance_fee": 40000,
    "maintenance_included": false,
    "floor": "1",
    "size": 0,
    "subway_station": "아시아드경기장역",
    "subway_minutes": 14,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "interphone",
      "elevator",
      "parking"
    ],
    "description": "Инчонд кошир тусдаа 2өрөө байр✨✨✨\n📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт\nБарьцаа:500,000\nТүрээс:500,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594256106,
    "payment_type": "quarterly",
    "latitude": 37.55095,
    "longitude": 126.69262,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777594146075_gxg6f",
    "title": "Инчонд кошир тусдаа 2өрөө байр✨✨✨ 📍인천광역시 서구 공촌동 307-16 아주하이빌 101동 1 давхарт Барьцаа:500,000 Түрээс:500,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "",
    "address": "",
    "monthly_rent": 0,
    "deposit": 0,
    "maintenance_fee": 0,
    "maintenance_included": false,
    "floor": "",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777594146075,
    "payment_type": "monthly",
    "latitude": null,
    "longitude": null,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777525361937_rwbbx",
    "title": "Сөүлийн 상봉역руу 20мин зайд✨✨✨ 🏡кошир тусдаа 2 өрөө байр 📍서울특별시 중랑구 망우동 456-12  엠에이치파크빌  3давхарт Барьцаа:500,000 Түрэээс: 1,100,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 중랑구 망우동 456-12",
    "address": "서울특별시 중랑구 망우동 456-12",
    "monthly_rent": 950000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "3",
    "size": 0,
    "subway_station": "상봉역. 망우역",
    "subway_minutes": 20,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "parking",
      "elevator",
      "interphone",
      "ac",
      "washer"
    ],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777525361937,
    "payment_type": "monthly",
    "latitude": 37.60178,
    "longitude": 127.1054,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777524969685_s9ma4",
    "title": "Сөүл шиллимд 3 өрөө байр✨✨✨ 📍서울특별시 관악구 신림동 652-10 라임카운티  5давхарт Барьцаа:500,000 Түрээс: 850,000(3,3 сараар) ❗️сөх тог газ ус тусдаа ✅хяаг солино, шууд орж болно, очиж үзэж болно",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 관악구 신림동 652-10",
    "address": "서울특별시 관악구 신림동 652-10",
    "monthly_rent": 750000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "3",
    "size": 0,
    "subway_station": "서울대벤처타운역",
    "subway_minutes": 25,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "parking",
      "elevator",
      "interphone",
      "gasStove",
      "shoeRack"
    ],
    "description": "",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777524969685,
    "payment_type": "quarterly",
    "latitude": 37.4868971,
    "longitude": 126.928177,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777524721384_ia7l1",
    "title": "Шиллимд 4 өрөө байр",
    "room_type": "oneRoom",
    "city": "seoul",
    "area": "서울특별시 관악구 신림동 654-9",
    "address": "서울특별시 관악구 신림동 654-9",
    "monthly_rent": 850000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "5",
    "size": 0,
    "subway_station": "서울대벤처타운역",
    "subway_minutes": 25,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "parking",
      "shoeRack",
      "elevator",
      "interphone"
    ],
    "description": "Шиллимд кошир тусдаа 3 өрөө 2 угаалгын өрөөтэй байр\nБарьцаа: 500,000\nТүрээс: 850,000/3,3сараар/",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777524721384,
    "payment_type": "monthly",
    "latitude": 37.486897,
    "longitude": 126.928177,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777524252316_hznk4",
    "title": "Сөүлд кошир тусдаа 2 өрөө байр✨✨✨ 🚇Байршил  ~1р шугамын 독산역руу алхаад 14мин  ~2р шугамын 구로다지털단자역руу автобусаар 15мин (автобусны буудал 2мин алхаад л орно) 📍서울시 금천구 독산동1011-2 정우팰리스 비동 2давхарт  💶Төлбөр  ~ Барьцаа: 1,000,000 вон  ~ Түрээс: 900,000 вон(3,3 сараар) ❗️сөх тог газ ус тусдаа 🏡хөргөгч угаалгын машин эйркон байгаа  ✅Бүх байр хаяг солино гэрэа хийнэ",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울시 금천구 독산동1011-2",
    "address": "서울시 금천구 독산동1011-2",
    "monthly_rent": 850000,
    "deposit": 500000,
    "maintenance_fee": 60000,
    "maintenance_included": false,
    "floor": "2",
    "size": 0,
    "subway_station": "구로다지털단자역",
    "subway_minutes": 15,
    "bus_stop": "",
    "bus_minutes": 2,
    "available_from": "2026-04-30",
    "options": [
      "ac",
      "washer",
      "interphone",
      "shoeRack",
      "parking",
      "fridge",
      "gasStove",
      "elevator"
    ],
    "description": "Сөүлд кошир тусдаа 2 өрөө байр✨✨✨\n🚇Байршил\n ~1р шугамын 독산역руу алхаад 14мин\n ~2р шугамын 구로다지털단자역руу автобусаар 15мин (автобусны буудал 2мин алхаад л орно)\n📍서울시 금천구 독산동1011-2 정우팰리스 비동 2давхарт \n💶Төлбөр\n ~ Барьцаа: 1,000,000 вон\n ~ Түрээс: 900,000 вон(3,3 сараар)\n❗️сөх тог газ ус тусдаа\n🏡хөргөгч угаалгын машин эйркон байгаа \n✅Бүх байр хаяг солино гэрэа хийнэ",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777524252316,
    "payment_type": "monthly",
    "latitude": 37.468399,
    "longitude": 126.8979571,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777472038238_alywt",
    "title": "Сөүлд кошир тусдаа 2 өрөө байр 📍서울시 금천구 독산동 913-2 대신하우스 1 давхар Барьцаа:500,000 Түрээс:850,000(3,3 сараар) ❗️сөх тог газ ус тусдаа шууд очоод үзэж болно шууд нүүж орход бэлэн хаяг солино жилийн гэрээ хийх боломжтой",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울시 금천구 독산동 913-2",
    "address": "서울시 금천구 독산동 913-2",
    "monthly_rent": 800000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "1.5",
    "size": 0,
    "subway_station": "구로디지털단지역",
    "subway_minutes": 19,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "",
    "options": [
      "에어컨  세탁기 냉장고"
    ],
    "description": "Сөүлд кошир тусдаа 2 өрөө байр\n📍서울시 금천구 독산동 913-2 대신하우스 1 давхар\nБарьцаа:500,000\nТүрээс:850,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа\nшууд очоод үзэж болно шууд нүүж орход бэлэн\nхаяг солино\nжилийн гэрээ хийх боломжтой",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777472038238,
    "payment_type": "quarterly",
    "latitude": 37.468399,
    "longitude": 126.8979571,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777468544044_kjcsu",
    "title": "Сөүлийн 🚇7р шугам 면목역 дээр 2 өрөө байр✨✨✨ 📍서울특별시 중랑구 면목동 116-2외 5필지 하이원팰리스 제102동 제7층  Барьцаа:500,000 Түрээс:900,000(3,3 сараар) ❗️сөх тог газ ус тусдаа хөргөгч угаалгын машин эйрконтойгоо",
    "room_type": "twoRoom",
    "city": "seoul",
    "area": "서울특별시 중랑구 면목동 116-2",
    "address": "서울특별시 중랑구 면목동 116-2",
    "monthly_rent": 900000,
    "deposit": 500000,
    "maintenance_fee": 70000,
    "maintenance_included": false,
    "floor": "7",
    "size": 0,
    "subway_station": "면목역",
    "subway_minutes": 4,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "냉장고 세탁기  천장에어컨   가스렌지"
    ],
    "description": "Сөүлийн 🚇7р шугам 면목역 дээр 2 өрөө байр✨✨✨\n📍서울특별시 중랑구 면목동 116-2외 5필지 하이원팰리스 제102동 제7층 \nБарьцаа:500,000\nТүрээс:900,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа\nхөргөгч угаалгын машин эйрконтойгоо",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777468544044,
    "payment_type": "quarterly",
    "latitude": 37.58178,
    "longitude": 127.09034,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777467765877_vkbxm",
    "title": "Сөүл дуксанд 3 өрөө байр🌿 📍서울특별시 금천구 독산동 1057 롯데블르빌 제5층  Барьцаа: 500,000 Түрээс: 850,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 금천구 독산동 1057",
    "address": "서울특별시 금천구 독산동 1057",
    "monthly_rent": 800000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "4",
    "size": 0,
    "subway_station": "구로디지털단지역",
    "subway_minutes": 20,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [],
    "description": "신발장 싱크대 인덕션",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777467765877,
    "payment_type": "quarterly",
    "latitude": 37.468399,
    "longitude": 126.8979571,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777467450574_tgefh",
    "title": "Сөүлийн 7р шугам 🚇 천왕역руу алхаад 11 мин зайд 🏡2 өрөө 복층 байр 📍서울특별시 구로구 천왕동 277-6 더메종277  Барьцаа: 500,000 Түрээс: 850,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "twoRoom",
    "city": "seoul",
    "area": "서울특별시 구로구 천왕동 277-6",
    "address": "서울특별시 구로구 천왕동 277-6",
    "monthly_rent": 750000,
    "deposit": 500000,
    "maintenance_fee": 70000,
    "maintenance_included": false,
    "floor": "9",
    "size": 0,
    "subway_station": "천왕역",
    "subway_minutes": 11,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "인덕션 싱크대 냉장고 세탁기 에어컨 신발장"
    ],
    "description": "Сөүлийн 7р шугам 🚇 천왕역руу алхаад 11 мин зайд\n🏡2 өрөө 복층 байр\n📍서울특별시 구로구 천왕동 277-6 더메종277 \nБарьцаа: 500,000\nТүрээс: 850,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777467450574,
    "payment_type": "quarterly",
    "latitude": 37.4809508,
    "longitude": 126.8389546,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777467272809_385i4",
    "title": "🚇천호역ийн 8р гарц дээр 🏡гал тогоо тусдаа нэг өрөө байр 📍서울특별시 강동구 성내동 81-10외 1필지 마이플레이스성내 4 давхарт Барьцаа:500,000 Түрээс:800,000(3,3 сараар) ❗️сөх тог газ тусдаа сөх 70,000~90,000 орчим 🌿хөргөгч угаалгын машин эйркон байгаа тог нээгээд гэрэл асаавал илүү тохилог🙂‍↔️",
    "room_type": "twoRoom",
    "city": "seoul",
    "area": "서울특별시 강동구 성내동 81-10",
    "address": "서울특별시 강동구 성내동 81-10",
    "monthly_rent": 700000,
    "deposit": 500000,
    "maintenance_fee": 60000,
    "maintenance_included": false,
    "floor": "4",
    "size": 0,
    "subway_station": "천호역",
    "subway_minutes": 3,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "에어컨 냉장고 세탁기  헹거옷장"
    ],
    "description": "🚇천호역ийн 8р гарц дээр\n🏡гал тогоо тусдаа нэг өрөө байр\n📍서울특별시 강동구 성내동 81-10외 1필지 마이플레이스성내 4 давхарт\nБарьцаа:500,000\nТүрээс:800,000(3,3 сараар)\n❗️сөх тог газ тусдаа\nсөх 70,000~90,000 орчим\n🌿хөргөгч угаалгын машин эйркон байгаа\nтог нээгээд гэрэл асаавал илүү тохилог🙂‍↔️",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777467272809,
    "payment_type": "quarterly",
    "latitude": 37.52998,
    "longitude": 127.12875,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777466900736_32gc9",
    "title": "Сөүл гүрод кошир тусдаа 3 өрөө байр✨✨✨ 🚇1,7р шугамын 온수역руу алхаад 13 мин 📍서울특별시 구로구 온수동 86-10 에코그린빌  5,6 давхруудад Барьцаа:500,000 Түрээс: 1,000,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 구로구 온수동 86-10",
    "address": "서울특별시 구로구 온수동 86-10",
    "monthly_rent": 850000,
    "deposit": 500000,
    "maintenance_fee": 40000,
    "maintenance_included": false,
    "floor": "6",
    "size": 0,
    "subway_station": "온수역",
    "subway_minutes": 13,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "인덕션 가스레인지 신발장 아일랜드식탁"
    ],
    "description": "Сөүл гүрод кошир тусдаа 3 өрөө байр✨✨✨\n🚇1,7р шугамын 온수역руу алхаад 13 мин\n📍서울특별시 구로구 온수동 86-10 에코그린빌 \n5,6 давхруудад\nБарьцаа:500,000\nТүрээс: 1,000,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777466900736,
    "payment_type": "quarterly",
    "latitude": 37.4945527,
    "longitude": 126.820444,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777466788548_xk4ov",
    "title": "Сөүл гүрод кошир тусдаа 3 өрөө байр✨✨✨ 🚇1,7р шугамын 온수역руу алхаад 13 мин 📍서울특별시 구로구 온수동 86-10 에코그린빌  5,6 давхруудад Барьцаа:500,000 Түрээс: 1,000,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 구로구 온수동 86-10",
    "address": "서울특별시 구로구 온수동 86-10",
    "monthly_rent": 850000,
    "deposit": 500000,
    "maintenance_fee": 40000,
    "maintenance_included": false,
    "floor": "5",
    "size": 0,
    "subway_station": "온수역",
    "subway_minutes": 13,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "인덕션 가스레인지 신발장 아일랜드식탁 에어컨"
    ],
    "description": "Сөүл гүрод кошир тусдаа 3 өрөө байр✨✨✨\n🚇1,7р шугамын 온수역руу алхаад 13 мин\n📍서울특별시 구로구 온수동 86-10 에코그린빌 \n5,6 давхруудад\nБарьцаа:500,000\nТүрээс: 1,000,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777466788548,
    "payment_type": "monthly",
    "latitude": 37.4945527,
    "longitude": 126.820444,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777466482708_si5ui",
    "title": "Сөүл гүрод кошир тусдаа 2 өрөө байр🌿 🚇1р шугамын 오류도역руу алхаад 15мин, 🚇1,7р шугамын 온수역ру автобусаар 16мин  📍서울특별시 구로구 오류동 4-75 금반석씨티빌41차 제5층  Барьцаа:500,000 Түрээс:900,000(3,3 сараар) ❗️сөх трг газ ус тусдаа сөх 50,000( илүү гарч болно) обой сольж өгнө",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 구로구 오류동 4-75",
    "address": "서울특별시 구로구 오류동 4-75",
    "monthly_rent": 800000,
    "deposit": 500000,
    "maintenance_fee": 60000,
    "maintenance_included": false,
    "floor": "5",
    "size": 0,
    "subway_station": "오류동역",
    "subway_minutes": 15,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "에어컨 신발장 인덕션 싱크댜"
    ],
    "description": "Сөүл гүрод кошир тусдаа 2 өрөө байр🌿\n🚇1р шугамын 오류도역руу алхаад 15мин, 🚇1,7р шугамын 온수역ру автобусаар 16мин\n 📍서울특별시 구로구 오류동 4-75 금반석씨티빌41차 제5층 \nБарьцаа:500,000\nТүрээс:900,000(3,3 сараар)\n❗️сөх трг газ ус тусдаа\nсөх 50,000( илүү гарч болно)\nобой сольж өгнө",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777466482708,
    "payment_type": "quarterly",
    "latitude": 37.4910095,
    "longitude": 126.8377379,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777466252275_qu6g8",
    "title": "Сөүлийн 7р шугам 🚇 천왕역руу алхаад 11 мин зайд 🏡2 өрөө 복층 байр 📍서울특별시 구로구 천왕동 277-6 더메종277  Барьцаа: 500,000 Түрээс: 850,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "officetel",
    "city": "seoul",
    "area": "서울특별시 구로구 천왕동 277-6",
    "address": "서울특별시 구로구 천왕동 277-6",
    "monthly_rent": 750000,
    "deposit": 500000,
    "maintenance_fee": 70000,
    "maintenance_included": false,
    "floor": "4",
    "size": 0,
    "subway_station": "천왕역",
    "subway_minutes": 11,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [],
    "description": "인덕션 싱크대 냉장고 세탁기 에어컨 신발장",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777466252275,
    "payment_type": "quarterly",
    "latitude": 37.4809508,
    "longitude": 126.8389546,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777465727264_srptd",
    "title": "Сөүл дуксанд 3 өрөө байр🌿 📍서울특별시 금천구 독산동 1057 롯데블르빌 제5층  Барьцаа: 500,000 Түрээс: 850,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 금천구 독산동 1057",
    "address": "서울특별시 금천구 독산동 1057",
    "monthly_rent": 750000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "5",
    "size": 0,
    "subway_station": "구로디지털단지역",
    "subway_minutes": 20,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "aircondition"
    ],
    "description": "Сөүл дуксанд 3 өрөө байр🌿\n📍서울특별시 금천구 독산동 1057 롯데블르빌 제5층 \nБарьцаа: 500,000\nТүрээс: 850,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777465727264,
    "payment_type": "quarterly",
    "latitude": 37.468399,
    "longitude": 126.8979571,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777400430292_dlmpf",
    "title": "Сөүл сүюүд 🚇삼양역руу алхаад 11мин зайд 🏡гал тогоо тусдаа 2 өрөө байр 📍서울특별시 강북구 수유동 475-134 행복한집 제4층  Барьцаа:500,000 Түрээс:950,000(3,3 сараар) ❗️сөх тог газ ус тусдаа обой сольж өгнө",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "서울특별시 강북구 수유동 475-134",
    "address": "서울특별시 강북구 수유동 475-134",
    "monthly_rent": 950000,
    "deposit": 500000,
    "maintenance_fee": 50000,
    "maintenance_included": false,
    "floor": "4",
    "size": 0,
    "subway_station": "삼양역",
    "subway_minutes": 11,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-29",
    "options": [
      "Эйркон",
      "газан плитка"
    ],
    "description": "Сөүл сүюүд 🚇삼양역руу алхаад 11мин зайд\n🏡гал тогоо тусдаа 2 өрөө байр\n📍서울특별시 강북구 수유동 475-134 행복한집 제4층 \nБарьцаа:500,000\nТүрээс:950,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа\nобой сольж өгнө",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777400430292,
    "payment_type": "quarterly",
    "latitude": 37.636597,
    "longitude": 127.0043825,
    "title_translations": {},
    "description_translations": {
      "en": "Seoul Suyudong 🚇11 min walk to Samyang Station\n🏡2 room apartment with separate kitchen\n📍4th Floor, Haengbokhanjib, 475-134 Suyu-dong, Gangbuk-gu, Seoul\nDeposit: 500,000\nRent: 950,000 (for 3.3 months)\n❗️Maintenance fee, electricity, gas and water are separate\nWallpaper will be changed",
      "ko": "서울 수유동 🚇삼양역에서 도보 11분 거리\n🏡주방 분리형 방 2개 아파트\n📍서울특별시 강북구 수유동 475-134 행복한집 4층\n보증금: 500,000\n월세: 950,000 (3.3개월)\n❗️관리비, 전기세, 가스비, 수도세 별도\n벽지 교체해 드립니다.",
      "ru": "Сеул, Сую-дон 🚇11 минут пешком до станции Самъян\n🏡2-комнатная квартира с отдельной кухней\n📍4-й этаж, Хэнбокханчиб, 475-134 Сую-дон, Канбук-гу, Сеул\nДепозит: 500,000\nАрендная плата: 950,000 (на 3,3 месяца)\n❗️Коммунальные услуги, электричество, газ и вода оплачиваются отдельно\nОбои поменяем",
      "vi": "Seoul Suyudong 🚇11 phút đi bộ đến Ga Samyang\n🏡Căn hộ 2 phòng có bếp riêng\n📍Tầng 4, Haengbokhanjib, 475-134 Suyu-dong, Gangbuk-gu, Seoul\nĐặt cọc: 500.000\nThuê: 950.000 (3,3 tháng)\n❗️Phí quản lý, tiền điện, gas và nước riêng\nSẽ thay đổi giấy dán tường",
      "zh": "首尔水逾洞 🚇步行11分钟到三阳站\n🏡两室一厅独立厨房公寓\n📍首尔特别市江北区水逾洞475-134 幸福家 第4层\n押金: 500,000\n租金: 950,000 (3.3个月)\n❗️管理费、电费、煤气费、水费另计\n提供更换壁纸"
    },
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777381151673_zxn3v",
    "title": "Бүпёнд нэг өрөө байр",
    "room_type": "oneRoom",
    "city": "incheon",
    "area": "부평구 부평동 378-1",
    "address": "인천광역시 부평구 부평동 378-1 부흥빌딩 1006호 공동 벨누르고 1",
    "monthly_rent": 500000,
    "deposit": 500000,
    "maintenance_fee": 80000,
    "maintenance_included": false,
    "floor": "10",
    "size": 0,
    "subway_station": "",
    "subway_minutes": 0,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-28",
    "options": [],
    "description": "хөргөгч угаалгын машин эйркон",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777381151673,
    "payment_type": "quarterly",
    "latitude": 37.4906976,
    "longitude": 126.723817,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  },
  {
    "id": "l_1777375410780_e2eyu",
    "title": "🚇2р шугамын 구로디지털단지역руу 18мин(автобусаар) 🏡кошир тусдаа 2 өрөө байр 📍서울특별시 금천구 독산동 1158(라온) 101동 4층 Барьцаа:500,000 Түрээс:800,000(3,3 сараар) ❗️сөх тог газ ус тусдаа",
    "room_type": "threeRoom",
    "city": "seoul",
    "area": "독산동",
    "address": "서울특별시 금천구 독산동 1158",
    "monthly_rent": 800000,
    "deposit": 500000,
    "maintenance_fee": 60000,
    "maintenance_included": false,
    "floor": "4",
    "size": 0,
    "subway_station": "구로디지털단지역",
    "subway_minutes": 18,
    "bus_stop": "",
    "bus_minutes": 0,
    "available_from": "2026-04-28",
    "options": [
      "хөргөгч угаалгын машиг эйркон"
    ],
    "description": "🚇2р шугамын 구로디지털단지역руу 18мин(автобусаар)\n🏡кошир тусдаа 2 өрөө байр\n📍서울특별시 금천구 독산동 1158(라온) 101동 4층\nБарьцаа:500,000\nТүрээс:800,000(3,3 сараар)\n❗️сөх тог газ ус тусдаа",
    "photos": [],
    "naver_map_url": null,
    "messenger_url": null,
    "status": "available",
    "featured": false,
    "created_at": 1777375410780,
    "payment_type": "monthly",
    "latitude": 37.4662458,
    "longitude": 126.8904839,
    "title_translations": {},
    "description_translations": {},
    "address_translations": {},
    "area_translations": {},
    "options_translations": {}
  }
] as const;
